# Generated by Django 4.0.3 on 2022-07-07 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_title', models.CharField(max_length=120)),
                ('cmp_deadline', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_title', models.CharField(max_length=120)),
                ('News_type', models.CharField(max_length=120)),
                ('News_time', models.CharField(max_length=120)),
                ('News_date', models.CharField(max_length=120)),
                ('News_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('News_detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompetitions',
            fields=[
                ('User_FirstName', models.CharField(max_length=120)),
                ('User_LastName', models.CharField(max_length=120)),
                ('User_Street_Address', models.CharField(max_length=120)),
                ('User_Address_Line', models.CharField(max_length=120)),
                ('User_City', models.CharField(max_length=120)),
                ('User_State', models.CharField(max_length=120)),
                ('User_Zip', models.CharField(max_length=120)),
                ('User_Country', models.CharField(max_length=120)),
                ('User_email', models.EmailField(max_length=120)),
                ('User_phone', models.CharField(max_length=120)),
                ('User_Location', models.CharField(max_length=120)),
                ('User_consent', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_detail', models.CharField(max_length=120)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_delivery_address', models.CharField(max_length=120)),
                ('order_delivery_time', models.DateTimeField()),
                ('order_notes', models.CharField(max_length=120)),
                ('category', models.ManyToManyField(to='account.category')),
                ('product', models.ManyToManyField(to='account.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_no_of_items', models.IntegerField()),
                ('cart_total', models.IntegerField()),
                ('category', models.ManyToManyField(to='account.category')),
                ('product', models.ManyToManyField(to='account.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
