# Generated by Django 4.0.3 on 2022-07-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usercompetitions_id_alter_usercompetitions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='cmp_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
