# Generated by Django 4.0.3 on 2022-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_newsletter_id_alter_newsletter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=120)),
                ('Cart_Id', models.CharField(max_length=120)),
                ('Product_Id', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
    ]
