# Generated by Django 4.0.3 on 2022-07-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='product_quantity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Cart_Id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Product_Id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='User_Id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
